copyright: 2019 Author name here
maintainer: example@example.com
name: solve-kyopro-with-haskell
version: 0.1.0.0
extra-source-files:
- README.md
author: Author name here
github: githubuser/solve-kyopro-with-haskell
license: BSD3
description: Please see the README on GitHub at <https://github.com/githubuser/solve-kyopro-with-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- array

library:
  source-dirs: src

tests:
  solve-kyopro-with-haskell-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solve-kyopro-with-haskell

executables:
  solve-kyopro-with-haskell-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transformers
    - transformers
    - solve-kyopro-with-haskell
